name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-native:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked
      - name: Package
        shell: bash
        run: |
          set -eux
          mkdir -p dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/weakssl.exe "dist/weakssl-windows-${{ runner.arch }}.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp target/release/weakssl "dist/weakssl-macos-${{ runner.arch }}"
          else
            cp target/release/weakssl "dist/weakssl-linux-${{ runner.arch }}"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weakssl-${{ runner.os }}-${{ runner.arch }}
          path: dist/*

  build-linux-arm64:
    name: Build (ubuntu-22.04-arm64)
    runs-on: ubuntu-22.04-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked
      - name: Package
        run: |
          mkdir -p dist
          cp target/release/weakssl dist/weakssl-linux-ARM64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weakssl-linux-ARM64
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-native, build-linux-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Prepare assets
        run: |
          ls -R dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/weakssl*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
