name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-native:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weakssl-${{ runner.os }}
          path: |
            target/release/weakssl
            target/release/weakssl.exe

  build-linux-arm64:
    name: Build (ubuntu-22.04-arm64)
    runs-on: ubuntu-22.04-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weakssl-ubuntu-arm64
          path: target/release/weakssl

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-native, build-linux-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Prepare assets
        run: |
          ls -R dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/weakssl
            dist/**/weakssl.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

